---
title: Aleatoriedad en Python
hero_image: images/banner.png
description: C칩mo utilizar el m칩dulo aleatorio de la biblioteca est치ndar de Python
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technology: "python"
steps:
  - title: El m칩dulo aleatorio
