---
title: 파이썬에서의 랜덤
hero_image: images/banner.png
description: 파이썬 표준 라이브러리에서 랜덤 모듈을 사용하는 방법
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technology: "python"
steps:
  - title: 랜덤 모듈
