---
title: L'aléatoire en Python
hero_image: images/banner.png
description: Comment utiliser le module random de la bibliothèque standard Python
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technology: "python"
steps:
  - title: Le module random
